python main.py --root_path ~/data \
	--video_path nturgb/jpg \
	--annotation_path ntu_01.json \
	--result_path results \
	--dataset ntu \
	--n_classes 9 \
	--resume_path models/km_model.pth \
	--model resnet \
	--model_depth 101 \
	--batch_size 80 \
	--n_threads 4 \
	--checkpoint 5 \
	--inference \
	--inference_subset val \
	--no_train \
	--no_val 
